import { LagoonProject, ServiceType } from './types';

export interface ServiceTypeInfo {
  image: string;          // default base image
  build: boolean;         // generate a Dockerfile instead of pulling the image directly
  cliBuildArg: boolean;   // multi-stage build copying /app from the cli image
  persistent?: string;    // default lagoon.persistent path
  persistentName?: string;
  routes: boolean;        // gets autogenerated routes → joins amazeeio-network locally
  appVolume: boolean;     // mount .:/app:delegated for local dev
  buildSteps: string;     // default Dockerfile RUN steps, one per line
}

const db = (image: string): ServiceTypeInfo =>
  ({ image, build: false, cliBuildArg: false, routes: false, appVolume: false, buildSteps: '' });

// Per-type defaults; see https://docs.lagoon.sh/concepts-advanced/service-types/
export const SERVICE_DEFAULTS: Record<ServiceType, ServiceTypeInfo> = {
  basic: { image: 'uselagoon/commons:latest', build: true, cliBuildArg: false, routes: true, appVolume: true, buildSteps: '' },
  'basic-persistent': { image: 'uselagoon/commons:latest', build: true, cliBuildArg: false, persistent: '/app/files/', routes: true, appVolume: true, buildSteps: '' },
  cli: { image: 'uselagoon/php-8.4-cli-drupal:latest', build: true, cliBuildArg: false, routes: false, appVolume: true, buildSteps: 'composer install --no-dev' },
  'cli-persistent': { image: 'uselagoon/php-8.4-cli-drupal:latest', build: true, cliBuildArg: false, persistent: '/app/web/sites/default/files/', persistentName: 'nginx', routes: false, appVolume: true, buildSteps: 'composer install --no-dev' },
  elasticsearch: db('uselagoon/elasticsearch-7:latest'),
  mariadb: db('uselagoon/mariadb-11.4:latest'),
  'mariadb-single': db('uselagoon/mariadb-11.4:latest'),
  'mariadb-dbaas': db('uselagoon/mariadb-11.4:latest'),
  mongodb: db('uselagoon/mongo-4:latest'),
  'mongodb-single': db('uselagoon/mongo-4:latest'),
  'mongodb-dbaas': db('uselagoon/mongo-4:latest'),
  nginx: { image: 'uselagoon/nginx:latest', build: true, cliBuildArg: true, routes: true, appVolume: true, buildSteps: '' },
  'nginx-php': { image: 'uselagoon/nginx-drupal:latest', build: true, cliBuildArg: true, routes: true, appVolume: true, buildSteps: '' },
  'nginx-php-persistent': { image: 'uselagoon/nginx-drupal:latest', build: true, cliBuildArg: true, persistent: '/app/web/sites/default/files/', routes: true, appVolume: true, buildSteps: '' },
  node: { image: 'uselagoon/node-24:latest', build: true, cliBuildArg: false, routes: true, appVolume: true, buildSteps: 'npm ci\nnpm run build' },
  'node-persistent': { image: 'uselagoon/node-24:latest', build: true, cliBuildArg: false, persistent: '/app/files/', routes: true, appVolume: true, buildSteps: 'npm ci\nnpm run build' },
  opensearch: db('uselagoon/opensearch-3:latest'),
  postgres: db('uselagoon/postgres-17:latest'),
  'postgres-single': db('uselagoon/postgres-17:latest'),
  'postgres-dbaas': db('uselagoon/postgres-17:latest'),
  python: { image: 'uselagoon/python-3.13:latest', build: true, cliBuildArg: false, routes: true, appVolume: true, buildSteps: 'pip install -r requirements.txt' },
  'python-persistent': { image: 'uselagoon/python-3.13:latest', build: true, cliBuildArg: false, persistent: '/app/files/', routes: true, appVolume: true, buildSteps: 'pip install -r requirements.txt' },
  redis: db('uselagoon/redis-8:latest'),
  'redis-persistent': db('uselagoon/redis-7-persistent:latest'),
  solr: db('uselagoon/solr-9:latest'),
  valkey: db('uselagoon/valkey-8:latest'),
  'valkey-persistent': db('uselagoon/valkey-8:latest'),
  varnish: db('uselagoon/varnish-8:latest'),
  'varnish-persistent': db('uselagoon/varnish-8:latest'),
  worker: { image: 'uselagoon/php-8.4-cli-drupal:latest', build: true, cliBuildArg: true, routes: false, appVolume: true, buildSteps: '' },
  'worker-persistent': { image: 'uselagoon/php-8.4-cli-drupal:latest', build: true, cliBuildArg: true, routes: false, appVolume: true, buildSteps: '' },
  none: { image: '', build: false, cliBuildArg: false, routes: false, appVolume: false, buildSteps: '' },
};

const service = (name: string, type: ServiceType, overrides: Partial<LagoonProject['services'][number]> = {}) => {
  const d = SERVICE_DEFAULTS[type];
  return {
    name,
    type,
    image: d.image,
    persistent: d.persistent ?? '',
    persistentName: d.persistentName ?? '',
    persistentSize: '',
    lagoonName: '',
    autogeneratedRoute: '' as const,
    port: '',
    buildSteps: d.buildSteps,
    ...overrides,
  };
};

const baseProject = {
  gitSha: false,
  autogenerateEnabled: true,
  autogenerateInsecure: 'Redirect' as const,
  autogeneratePrefixes: '',
  autogenerateAllowPullrequests: true,
  backupsEnabled: false,
  backupSchedule: 'M H(22-2) * * *',
  backupRetention: { hourly: 0, daily: 7, weekly: 6, monthly: 0 },
  containerRegistries: [],
};

export const PRESETS: Record<string, LagoonProject> = {
  Drupal: {
    ...baseProject,
    projectName: 'my-drupal-project',
    services: [
      service('cli', 'cli-persistent'),
      service('nginx', 'nginx-php-persistent', { image: 'uselagoon/nginx-drupal:latest' }),
      service('php', 'nginx-php-persistent', { image: 'uselagoon/php-8.4-fpm:latest', lagoonName: 'nginx' }),
      service('mariadb', 'mariadb', { image: 'uselagoon/mariadb-10.11-drupal:latest' }),
    ],
    tasks: {
      preRollout: [
        { name: 'drush sql-dump', command: 'mkdir -p /app/web/sites/default/files/private/ && drush sql-dump --ordered-dump --gzip --result-file=/app/web/sites/default/files/private/pre-deploy-dump.sql.gz || true', service: 'cli', container: '', shell: '', when: '' },
      ],
      postRollout: [
        { name: 'drush deploy', command: 'if [[ $(drush status --field=Database) == "Connected" ]]; then drush -y deploy; fi', service: 'cli', shell: 'bash', container: '', when: '' },
      ],
    },
    environments: [
      {
        name: 'main',
        autogenerateRoutes: '',
        cronjobs: [{ name: 'drush cron', schedule: 'M/15 * * * *', command: 'drush cron', service: 'cli' }],
        routes: [],
      },
    ],
  },
  Laravel: {
    ...baseProject,
    projectName: 'my-laravel-project',
    services: [
      service('cli', 'cli-persistent', { persistent: '/app/storage/' }),
      service('nginx', 'nginx-php-persistent', { image: 'uselagoon/nginx:latest', persistent: '/app/storage/' }),
      service('php', 'nginx-php-persistent', { image: 'uselagoon/php-8.4-fpm:latest', lagoonName: 'nginx', persistent: '/app/storage/' }),
      service('mariadb', 'mariadb'),
      service('redis', 'redis'),
    ],
    tasks: {
      preRollout: [],
      postRollout: [
        { name: 'Run migrations', command: 'php artisan migrate --force', service: 'cli', container: '', shell: '', when: '' },
        { name: 'Cache config', command: 'php artisan config:cache && php artisan optimize', service: 'cli', container: '', shell: '', when: '' },
      ],
    },
    environments: [
      {
        name: 'main',
        autogenerateRoutes: '',
        cronjobs: [{ name: 'artisan scheduler', schedule: 'M/15 * * * *', command: 'php artisan schedule:run', service: 'cli' }],
        routes: [],
      },
    ],
  },
  'Node.js': {
    ...baseProject,
    projectName: 'my-node-project',
    services: [service('node', 'node')],
    tasks: { preRollout: [], postRollout: [] },
    environments: [{ name: 'main', autogenerateRoutes: '', cronjobs: [], routes: [] }],
  },
  Static: {
    ...baseProject,
    projectName: 'my-static-site',
    services: [service('nginx', 'nginx')],
    tasks: { preRollout: [], postRollout: [] },
    environments: [{ name: 'main', autogenerateRoutes: '', cronjobs: [], routes: [] }],
  },
};

export const LAGOON_EXAMPLES_ORG = 'lagoon-examples';
