import { LagoonProject, LagoonService, LagoonTask, LagoonRoute, GeneratedFile, volumeMounts } from './types';
import { SERVICE_DEFAULTS } from './constants';
import YAML from 'yaml';

const lines = (s?: string) => (s ?? '').split('\n').map(l => l.trim()).filter(Boolean);
const csv = (s?: string) => (s ?? '').split(',').map(p => p.trim()).filter(Boolean);

function formatTask(task: LagoonTask) {
  const run: any = { name: task.name, command: task.command, service: task.service };
  if (task.container) run.container = task.container;
  if (task.shell) run.shell = task.shell;
  if (task.when) run.when = task.when;
  if (task.weight && Number(task.weight) !== 0) run.weight = Number(task.weight);
  return { run };
}

function formatRoute(route: LagoonRoute): string | Record<string, any> {
  const opts: any = {};
  if (!route.tlsAcme) opts['tls-acme'] = false;
  if (route.insecure !== 'Redirect') opts.insecure = route.insecure;
  if (route.hstsEnabled) {
    opts.hstsEnabled = true;
    opts.hstsMaxAge = route.hstsMaxAge;
  }
  if (route.monitoringPath) opts['monitoring-path'] = route.monitoringPath;
  const annotations = lines(route.annotations);
  if (annotations.length > 0) {
    opts.annotations = {};
    annotations.forEach(line => {
      const idx = line.indexOf(':');
      if (idx > 0) opts.annotations[line.slice(0, idx).trim()] = line.slice(idx + 1).trim();
    });
  }
  const altNames = csv(route.alternativeNames);
  if (altNames.length > 0) opts.alternativenames = altNames;
  if (route.wildcard) opts.wildcard = true;
  if (route.ingressClass) opts.ingressClass = route.ingressClass;
  if (route.pathRoutes.length > 0) opts.pathRoutes = route.pathRoutes.map(r => ({ toService: r.toService, path: r.path }));
  if (route.disableRequestVerification) opts.disableRequestVerification = true;
  return Object.keys(opts).length > 0 ? { [route.domain]: opts } : route.domain;
}

// routes is a list of single-key maps: service → list of domains/domain-maps
function formatRoutes(routes: LagoonRoute[]) {
  const byService = new Map<string, Array<string | Record<string, any>>>();
  routes.forEach(route => {
    if (!byService.has(route.service)) byService.set(route.service, []);
    byService.get(route.service)!.push(formatRoute(route));
  });
  return [...byService.entries()].map(([svc, domains]) => ({ [svc]: domains }));
}

const formatPathRoutes = (routes: LagoonProject['autogeneratePathRoutes']) =>
  routes.map(r => ({ fromService: r.fromService, toService: r.toService, path: r.path }));

export function generateLagoonYml(project: LagoonProject): string {
  const config: any = {
    'docker-compose-yaml': 'docker-compose.yml',
  };

  if (project.gitSha) {
    config.environment_variables = { git_sha: 'true' };
  }

  const autogenerate: any = {};
  if (!project.autogenerateEnabled) {
    autogenerate.enabled = false;
    if (project.autogenerateAllowPullrequests) autogenerate.allowPullrequests = true;
  }
  // always explicit: Lagoon defaults autogenerated routes to Allow (custom routes to Redirect)
  autogenerate.insecure = project.autogenerateInsecure;
  const prefixes = csv(project.autogeneratePrefixes);
  if (prefixes.length > 0) autogenerate.prefixes = prefixes;
  if (!project.autogenerateTlsAcme) autogenerate['tls-acme'] = false;
  if (project.autogenerateIngressClass) autogenerate.ingressClass = project.autogenerateIngressClass;
  if (project.autogeneratePathRoutes.length > 0) {
    autogenerate.pathRoutes = formatPathRoutes(project.autogeneratePathRoutes);
  }
  if (project.autogenerateDisableRequestVerification) autogenerate.disableRequestVerification = true;
  if (Object.keys(autogenerate).length > 0) {
    config.routes = { autogenerate };
  }

  const { active, standby } = project.productionRoutes;
  if (active.length > 0 || standby.length > 0) {
    config.production_routes = {};
    if (active.length > 0) config.production_routes.active = { routes: formatRoutes(active) };
    if (standby.length > 0) config.production_routes.standby = { routes: formatRoutes(standby) };
  }

  if (project.backupsEnabled) {
    config['backup-schedule'] = { production: project.backupSchedule };
    config['backup-retention'] = { production: { ...project.backupRetention } };
  }

  if (project.containerRegistries.length > 0) {
    config['container-registries'] = {};
    project.containerRegistries.forEach(reg => {
      const entry: any = {};
      if (reg.url) entry.url = reg.url;
      if (reg.username) entry.username = reg.username;
      // password comes from the REGISTRY_<NAME>_PASSWORD Lagoon variable — never hardcoded
      config['container-registries'][reg.name] = entry;
    });
  }

  if (project.tasks.preRollout.length > 0 || project.tasks.postRollout.length > 0) {
    config.tasks = {};
    if (project.tasks.preRollout.length > 0) {
      config.tasks['pre-rollout'] = project.tasks.preRollout.map(formatTask);
    }
    if (project.tasks.postRollout.length > 0) {
      config.tasks['post-rollout'] = project.tasks.postRollout.map(formatTask);
    }
  }

  if (project.environments.length > 0) {
    const environments: any = {};
    project.environments.forEach(env => {
      const envConfig: any = {};

      if (env.autogenerateRoutes) {
        envConfig.autogenerateRoutes = env.autogenerateRoutes === 'true';
      }

      if (env.types.length > 0) {
        envConfig.types = Object.fromEntries(env.types.map(t => [t.service, t.type]));
      }

      const overrides = env.overrides.filter(o => o.image || o.dockerfile);
      if (overrides.length > 0) {
        envConfig.overrides = Object.fromEntries(overrides.map(o => {
          const override: any = {};
          if (o.dockerfile) override.build = { dockerfile: o.dockerfile };
          if (o.image) override.image = o.image;
          return [o.service, override];
        }));
      }

      if (env.routes.length > 0) envConfig.routes = formatRoutes(env.routes);
      if (env.autogeneratePathRoutes.length > 0) envConfig.autogeneratePathRoutes = formatPathRoutes(env.autogeneratePathRoutes);

      if (env.cronjobs.length > 0) {
        envConfig.cronjobs = env.cronjobs.map(cron => {
          const c: any = { name: cron.name, schedule: cron.schedule, command: cron.command, service: cron.service };
          if (cron.inPod) c.inPod = cron.inPod === 'true';
          if (cron.timeout) c.timeout = cron.timeout;
          return c;
        });
      }

      if (Object.keys(envConfig).length > 0) environments[env.name] = envConfig;
    });
    if (Object.keys(environments).length > 0) config.environments = environments;
  }

  let output = YAML.stringify(config, { blockQuote: 'literal', lineWidth: 0 });
  // blank line between top-level sections
  output = output.replace(/\n([a-z][a-z-_]*):/g, '\n\n$1:');
  return output.trim() + '\n';
}

const needsBuild = (service: LagoonService) => SERVICE_DEFAULTS[service.type].build;
const needsCliImage = (service: LagoonService, hasCli: boolean) =>
  hasCli && SERVICE_DEFAULTS[service.type].cliBuildArg;

export function generateDockerCompose(project: LagoonProject): string {
  const info = (s: LagoonService) => SERVICE_DEFAULTS[s.type];
  const hasCli = project.services.some(s => s.type === 'cli' || s.type === 'cli-persistent');
  const cliService = project.services.find(s => s.type === 'cli' || s.type === 'cli-persistent');

  let out = `x-environment:
  &default-environment
    LAGOON_PROJECT: ${project.projectName}
    # Route that should be used locally
    LAGOON_ROUTE: &default-url http://\${COMPOSE_PROJECT_NAME:-${project.projectName}}.docker.amazee.io
    # Uncomment if you like to have the system behave like in production
    #LAGOON_ENVIRONMENT_TYPE: production
    # Uncomment to enable xdebug and then restart via \`docker compose up -d\`
    #XDEBUG_ENABLE: "true"

x-volumes:
  &default-volumes
    volumes:
      - .:/app:delegated

services:
`;

  // the &cli-image anchor must be defined before any *cli-image alias
  const ordered = [...project.services].sort(
    (a, b) => Number(!a.type.startsWith('cli')) - Number(!b.type.startsWith('cli'))
  );

  ordered.forEach(service => {
    const i = info(service);
    out += `
  ${service.name}:\n`;

    if (needsBuild(service)) {
      out += `    build:
      context: .
      dockerfile: lagoon/${service.name}.dockerfile\n`;
      if (needsCliImage(service, hasCli)) {
        out += `      args:
        CLI_IMAGE: *cli-image\n`;
      }
      if (service.type === 'cli' || service.type === 'cli-persistent') {
        out += `    image: &cli-image \${COMPOSE_PROJECT_NAME:-${project.projectName}}-cli\n`;
      }
    } else if (service.image) {
      out += `    image: ${service.image}\n`;
    }

    out += `    labels:
      lagoon.type: ${service.type}\n`;
    if (service.lagoonName) out += `      lagoon.name: ${service.lagoonName}\n`;
    if (service.persistent) out += `      lagoon.persistent: ${service.persistent}\n`;
    if (service.persistentName) out += `      lagoon.persistent.name: ${service.persistentName}\n`;
    if (service.persistentSize) out += `      lagoon.persistent.size: ${service.persistentSize}\n`;
    if (service.autogeneratedRoute) out += `      lagoon.autogeneratedroute: '${service.autogeneratedRoute}'\n`;
    if (service.port) out += `      lagoon.service.port: ${service.port}\n`;
    if (service.type === 'external') {
      const ext = Object.fromEntries(Object.entries(service.external ?? {}).filter(([, v]) => v));
      out += `      lagoon.external.service: '${JSON.stringify(ext).replace(/'/g, "''")}'\n`;
    }
    const mounts = volumeMounts(service.volumes);
    mounts.forEach(m => { out += `      lagoon.volumes.${m.volume}.path: ${m.path}\n`; });

    if (mounts.length > 0) {
      // a service-level volumes: key replaces the merged default, so repeat the app mount
      out += `    volumes:\n`;
      if (i.appVolume) out += `      - .:/app:delegated\n`;
      mounts.forEach(m => { out += `      - ${m.volume}:${m.path}\n`; });
    } else if (i.appVolume) {
      out += `    << : *default-volumes\n`;
    }
    if (needsCliImage(service, hasCli) && cliService) {
      out += `    depends_on:
      - ${cliService.name}\n`;
    }
    out += `    environment:
      << : *default-environment\n`;
    Object.entries(i.env ?? {}).forEach(([k, v]) => { out += `      ${k}: ${v}\n`; });
    if (i.routes) {
      out += `    networks:
      - amazeeio-network
      - default\n`;
    }
  });

  if (project.volumes.length > 0) {
    out += `\nvolumes:\n`;
    project.volumes.forEach(v => {
      out += `  ${v.name}:
    labels:
      lagoon.type: persistent\n`;
      if (v.size) out += `      lagoon.persistent.size: ${v.size}\n`;
      if (!v.backup) out += `      lagoon.backup: 'false'\n`;
    });
  }

  out += `
networks:
  amazeeio-network:
    external: true
`;
  return out;
}

export function generateDockerfile(service: LagoonService, hasCli: boolean): string {
  const image = service.image || SERVICE_DEFAULTS[service.type].image;
  const steps = lines(service.buildSteps);
  let content: string;

  if (needsCliImage(service, hasCli)) {
    content = `ARG CLI_IMAGE
FROM \${CLI_IMAGE} AS cli

FROM ${image}

COPY --from=cli /app /app
`;
  } else {
    content = `FROM ${image}

COPY . /app
`;
  }
  if (steps.length > 0) {
    content += `\nRUN ${steps.join(' \\\n    && ')}\n`;
  }
  return content;
}

export function generateAllFiles(project: LagoonProject): GeneratedFile[] {
  const hasCli = project.services.some(s => s.type === 'cli' || s.type === 'cli-persistent');
  const files: GeneratedFile[] = [
    { name: '.lagoon.yml', path: '.lagoon.yml', content: generateLagoonYml(project) },
    { name: 'docker-compose.yml', path: 'docker-compose.yml', content: generateDockerCompose(project) },
  ];

  project.services.forEach(service => {
    if (needsBuild(service)) {
      files.push({
        name: `${service.name}.dockerfile`,
        path: `lagoon/${service.name}.dockerfile`,
        content: generateDockerfile(service, hasCli),
      });
    }
  });

  return files;
}
