import { z } from 'zod';

// Full lagoon.type list from https://docs.lagoon.sh/concepts-advanced/service-types/
export const SERVICE_TYPES = [
  'basic',
  'basic-persistent',
  'cli',
  'cli-persistent',
  'elasticsearch',
  'mariadb',
  'mariadb-single',
  'mariadb-dbaas',
  'mongodb',
  'mongodb-single',
  'mongodb-dbaas',
  'nginx',
  'nginx-php',
  'nginx-php-persistent',
  'node',
  'node-persistent',
  'opensearch',
  'postgres',
  'postgres-single',
  'postgres-dbaas',
  'python',
  'python-persistent',
  'redis',
  'redis-persistent',
  'solr',
  'valkey',
  'valkey-persistent',
  'varnish',
  'varnish-persistent',
  'worker',
  'worker-persistent',
  'none',
] as const;

export const ServiceTypeSchema = z.enum(SERVICE_TYPES);
export type ServiceType = z.infer<typeof ServiceTypeSchema>;

export const LagoonTaskSchema = z.object({
  name: z.string().min(1, 'Task name is required'),
  command: z.string().min(1, 'Command is required'),
  service: z.string().min(1, 'Service is required'),
  container: z.string().optional(),
  shell: z.string().optional(),
  when: z.string().optional(),
});
export type LagoonTask = z.infer<typeof LagoonTaskSchema>;

export const LagoonCronjobSchema = z.object({
  name: z.string().min(1, 'Cronjob name is required'),
  schedule: z.string().min(1, 'Schedule is required'),
  command: z.string().min(1, 'Command is required'),
  service: z.string().min(1, 'Service is required'),
});
export type LagoonCronjob = z.infer<typeof LagoonCronjobSchema>;

export const LagoonRouteSchema = z.object({
  service: z.string().min(1),
  domain: z.string().min(1, 'Domain is required'),
  tlsAcme: z.boolean().default(true),
  insecure: z.enum(['Redirect', 'Allow']).default('Redirect'),
  hstsEnabled: z.boolean().default(false),
  hstsMaxAge: z.coerce.number().default(31536000),
  monitoringPath: z.string().optional(),
  // one "key: value" ingress annotation per line
  annotations: z.string().optional(),
});
export type LagoonRoute = z.infer<typeof LagoonRouteSchema>;

export const LagoonEnvironmentSchema = z.object({
  name: z.string().min(1, 'Environment name is required'),
  // '' = inherit global setting
  autogenerateRoutes: z.enum(['', 'true', 'false']).default(''),
  cronjobs: z.array(LagoonCronjobSchema).default([]),
  routes: z.array(LagoonRouteSchema).default([]),
});
export type LagoonEnvironment = z.infer<typeof LagoonEnvironmentSchema>;

export const LagoonServiceSchema = z.object({
  name: z.string().min(1, 'Service name is required'),
  type: ServiceTypeSchema,
  image: z.string().optional(),
  // lagoon.persistent / .name / .size labels
  persistent: z.string().optional(),
  persistentName: z.string().optional(),
  persistentSize: z.string().optional(),
  // lagoon.name — group this service into another service's pod
  lagoonName: z.string().optional(),
  // lagoon.autogeneratedroute label; '' = default
  autogeneratedRoute: z.enum(['', 'true', 'false']).default(''),
  // lagoon.service.port label
  port: z.string().optional(),
  // one shell command per line, run in the generated Dockerfile
  buildSteps: z.string().optional(),
});
export type LagoonService = z.infer<typeof LagoonServiceSchema>;

export const ContainerRegistrySchema = z.object({
  name: z.string().min(1, 'Registry name is required'),
  url: z.string().optional(),
  username: z.string().optional(),
});
export type ContainerRegistry = z.infer<typeof ContainerRegistrySchema>;

export const LagoonProjectSchema = z.object({
  projectName: z.string().min(1, 'Project name is required'),
  // environment_variables.git_sha
  gitSha: z.boolean().default(false),
  // routes.autogenerate
  autogenerateEnabled: z.boolean().default(true),
  autogenerateInsecure: z.enum(['Redirect', 'Allow']).default('Redirect'),
  autogeneratePrefixes: z.string().optional(), // comma separated
  autogenerateAllowPullrequests: z.boolean().default(true),
  // backup-schedule / backup-retention (production)
  backupsEnabled: z.boolean().default(false),
  backupSchedule: z.string().default('M H(22-2) * * *'),
  backupRetention: z.object({
    hourly: z.coerce.number().default(0),
    daily: z.coerce.number().default(7),
    weekly: z.coerce.number().default(6),
    monthly: z.coerce.number().default(0),
  }).default({ hourly: 0, daily: 7, weekly: 6, monthly: 0 }),
  containerRegistries: z.array(ContainerRegistrySchema).default([]),
  services: z.array(LagoonServiceSchema).min(1, 'At least one service is required'),
  tasks: z.object({
    preRollout: z.array(LagoonTaskSchema).default([]),
    postRollout: z.array(LagoonTaskSchema).default([]),
  }).default({ preRollout: [], postRollout: [] }),
  environments: z.array(LagoonEnvironmentSchema).default([]),
});
export type LagoonProject = z.infer<typeof LagoonProjectSchema>;
// form values before zod applies defaults/coercion
export type LagoonProjectInput = z.input<typeof LagoonProjectSchema>;

export interface GeneratedFile {
  name: string;
  content: string;
  path: string;
}

export interface LagoonExample {
  name: string;
  description: string;
  html_url: string;
}
